#!/bin/sh

export NODE_ENV="DEV"
if [ -f "../../server/.port" ]
then
  port=`cat ../../server/.port | head -1`
  echo "using port number $port from file .port"
  echo "mongo db will be dev$port"
  export ZESCORE_PORT=$port
  mocha -R spec --recursive
else
  echo "  Please create ../../server/.port file containing port number "
  echo "  Exemple:  echo \"15123\" > ../../server/.port "
fi

