#!/bin/sh

export NODE_ENV="DEV"
if [ -f "../../server/.port" ]
then
  port=`cat ../../server/.port | head -1`
  echo "using port number $port from file .port"
  echo "mongo db will be dev$port"
  export YESWESCORE_PORT=$port
  if [ $# -eq 1 ]
  then
    mocha -R spec -b $1
  else
    mocha -R spec --recursive
  fi
else
  echo "  Please create ../../server/.port file containing port number "
  echo "  Exemple:  echo \"15123\" > ../../server/.port "
fi

